/* autogenerated by Processing revision 1304 on 2026-02-18 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class CAT_UI extends PApplet {

// ==========================
// フィールド
// ==========================
Character character;
TextDisplay textDisplay;
float globalScale;

FaceIPC ipc;

// ==========================
// setup
// ==========================
public void setup() {
  /* size commented out by preprocessor */;
  /* smooth commented out by preprocessor */;

  // ★ 正しい IPC ルート（PC依存なし）
  println("IPC ROOT = " + dataPath("ipc"));

  globalScale = min(width / 400.0f, height / 300.0f);

  character = new Character(this, globalScale);
  textDisplay = new TextDisplay(this, globalScale);
  textDisplay.setAutoAdvance(true, 2.5f);

  try {
    // ★ ここが超重要：絶対に "ipc" を直接渡さない
    ipc = new FaceIPC(dataPath("ipc"));
  } catch (Exception e) {
    e.printStackTrace();
  }
}

// ==========================
// draw
// ==========================
public void draw() {
  background(0);

  handleIPC();

  character.update();
  character.draw();

  textDisplay.update();
  textDisplay.draw();
}

// ==========================
// IPC 処理
// ==========================
public void handleIPC() {
  if (ipc == null) return;

  try {
    for (UICommand cmd : ipc.poll()) {

      // face ID → 表情
      if (cmd.faceId >= 0) {
        character.setExpression(faceIdToExpression(cmd.faceId));
      }

      // テキスト表示
      if (cmd.text != null) {
        textDisplay.showMessage(cmd.text);
      }

      // reset_after
      if (cmd.resetAfter > 0) {
        scheduleReset(cmd.resetAfter);
      }
    }
  } catch (Exception e) {
    e.printStackTrace();
  }
}

// ==========================
// face ID → Expression
// ==========================
public String faceIdToExpression(int id) {
  switch (id) {
    case 0: return "NORMAL";
    case 1: return "QUESTION";
    case 2: return "HAPPY";
    case 3: return "SMILE";
    case 4: return "SLEEPING";
    default: return "NORMAL";
  }
}

// ==========================
// reset_after 処理
// ==========================
public void scheduleReset(float seconds) {
  int delayMs = PApplet.parseInt(seconds * 1000);

  new java.util.Timer().schedule(
    new java.util.TimerTask() {
      public void run() {
        character.setExpression("NORMAL");
      }
    },
    delayMs
  );
}

// ==========================
// キー入力（デバッグ用）!
// ==========================
public void keyPressed() {
  if (key == '1') {
    character.setExpression("QUESTION");
    textDisplay.showMessage("デバッグ入力");
    scheduleReset(2.0f);
  }
}


  public void settings() { fullScreen();
smooth(8); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "CAT_UI" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
